### ISSUE TITLE
Get Inspetor PHP lib ready for external integration

### ISSUE THREAD

**Issue by phsanzovo** [inspetor/inspetor-php#7]
(I know this is not in the right repo, but wasn't quite sure where to best put it -- open to feedback on this)

**Comment by pearsonhenri** [comment]
To link the sub-issues here:
- [ ] Add unit tests: https://github.com/inspetor/inspetor-php/issues/5
- [ ] Add integration tests: https://github.com/inspetor/inspetor-php/issues/4
- [ ] PHP SDK Documentation: https://github.com/inspetor/inspetor-php/issues/8
- [ ] Finalize publishing: https://github.com/inspetor/inspetor-php/issues/16

**Comment by pearsonhenri** [comment]
Going to keep this issue specific for PHP and add additional tracking issues in the corresponding lib repos

**Comment by pearsonhenri** [comment]
iOS issue: https://github.com/inspetor/inspetor-ios/issues/5
Android issue: https://github.com/inspetor/inspetor-android/issues/4
JS/Web tracking: https://github.com/inspetor/web-collector/issues/1 (this one is definitely a little hairier)

**Comment by pearsonhenri** [comment]
Going to close this issue--I think the issue itself is "done," and any necessary updates can be tracked in more granular, individual issues. 

Nice work here @lbiselli and @theosato  :)
